import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../../Component/Navbar/page";
import Sidebar from "../../Component/Sidebar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kashif Khalil Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        {/* Flex container for sidebar and content */}
        <div className="flex px-6 md:px-24 gap-5">
          {/* Sidebar takes 30% */}
          <div className="w-full md:w-1/3 lg:w-[35%]">
            <Sidebar />
          </div>

          {/* Main content takes remaining 70% */}
          <div className="w-full md:w-2/3 lg:w-[70%]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
